services:
  qwen2.5-3b:
    image: ghcr.io/ggml-org/llama.cpp:server
    ports:
      - "8080:8080"
    container_name: qwen2.5-3b
    volumes:
      - ../modelos/llm:/llm:ro
    command:
      - "--model"
      - "/llm/Qwen2.5-3B-Instruct-Q4_K_M.gguf"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "-c"
      - "4096"
      - "-ngl"
      - "99"
    restart: unless-stopped
    mem_limit: 4g
    networks:
      - llm-local-network

networks:
  llm-local-network:
    external: true
